name = "top5-worker"
main = "apps/worker/src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
GOOGLE_PLACES_API_KEY = ""
TURNSTILE_SECRET = ""

[triggers]
crons = ["*/10 * * * *"]

[[d1_databases]]
binding = "TOP5_DB"
database_name = "top5-db-prod"
database_id = "84d10342-f614-475c-bc45-e9b9889fb657"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "8f42998ce14f4ae880407cfe23dde0b1"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "top5-images-prod"

[dev]
port = 8787
local_protocol = "http"

[ai]
binding = "AI"
